[package]
name = "solfege"
version = "0.1.0"
edition = "2021"
description = "Data structures to represent music"
license = "MIT"
keywords = ["music", "notation"]
categories = ["data-structures"]

[dependencies]
